// <auto-generated />
using System;
using ApiAmaz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiAmaz.Migrations
{
    [DbContext(typeof(AmazDbContext))]
    [Migration("20220727070305_UserData")]
    partial class UserData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiAmaz.Model.IdentityDocumentType", b =>
                {
                    b.Property<string>("DocumentType")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("TIPODOCUMENTO");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREADOR");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHACREACION");

                    b.Property<DateTime>("DateUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHAMODIFICACION")
                        .HasComputedColumnSql("GetUtcDate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("NameShort")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOMBRECORTO");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFICADOR");

                    b.Property<bool>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ESTADO");

                    b.HasKey("DocumentType");

                    b.ToTable("TIPODOCUMENTOIDENTIDAD", (string)null);

                    b.HasData(
                        new
                        {
                            DocumentType = "00",
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(8785),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OTROS",
                            NameShort = "OTROS",
                            Updater = "admin",
                            isActive = false
                        },
                        new
                        {
                            DocumentType = "01",
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(8794),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LIBRETA ELECTORAL O DNI",
                            NameShort = "L.E / DNI",
                            Updater = "admin",
                            isActive = false
                        },
                        new
                        {
                            DocumentType = "04",
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(8796),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CARNET DE EXTRANJERIA",
                            NameShort = "CARNET EXT.",
                            Updater = "admin",
                            isActive = false
                        },
                        new
                        {
                            DocumentType = "06",
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(8798),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "REG. UNICO DE CONTRIBUYENTES",
                            NameShort = "RUC",
                            Updater = "admin",
                            isActive = false
                        },
                        new
                        {
                            DocumentType = "07",
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(8800),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PASAPORTE",
                            NameShort = "PASAPORTE",
                            Updater = "admin",
                            isActive = false
                        },
                        new
                        {
                            DocumentType = "11",
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(8803),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PART. DE NACIMIENTO-IDENTIDAD",
                            NameShort = "P. NAC.",
                            Updater = "admin",
                            isActive = false
                        });
                });

            modelBuilder.Entity("ApiAmaz.Model.Role", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREADOR");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHACREACION");

                    b.Property<DateTime>("DateUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHAMODIFICACION")
                        .HasComputedColumnSql("GetUtcDate()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ESTADO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFICADOR");

                    b.HasKey("Code");

                    b.ToTable("ROL", (string)null);

                    b.HasData(
                        new
                        {
                            Code = new Guid("8c8ae9ba-c1a2-45e0-a987-21788d423a74"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(1854),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "VENDEDOR",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("996d9004-ec56-4c67-9eef-9be6245f0da1"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(1873),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "ESTILISTA",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("4ced3476-e822-48ba-8c25-01e2029d1db1"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(1895),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "MARKETING",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("15f6b842-789c-4bd9-b931-80df31eeed93"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(1899),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "DESPACHADOR",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("80b91748-8b5b-4815-a189-ea25ae4c7c83"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(1902),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "COBRANZA",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("a791db19-3446-4fbe-b40c-8942c453aa15"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(1910),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "ADMINISTRATIVO",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("6ede3d80-167d-4f55-9828-706c1be3e9a9"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(1913),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "GERENTE COMERCIAL",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("7bc5f5aa-9e6f-4d35-9d7f-536a39bb2595"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(1916),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "GERENTE GENERAL",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("3627aa99-fb25-42d3-8ac5-aeff4f92d0db"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(1918),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "VENDEDOR FREE",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("5571a1d4-2fa3-4f3d-a6f9-4b97c5753cb0"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(1922),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "COORDINADOR",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("dcecaf47-895a-4adb-92b5-0a62336619eb"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 718, DateTimeKind.Local).AddTicks(1937),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "SUPERADMIN",
                            Updater = "admin"
                        });
                });

            modelBuilder.Entity("ApiAmaz.Model.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USUARIO");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CLAVE");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREADOR");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHACREACION");

                    b.Property<DateTime>("DateUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHAMODIFICACION")
                        .HasComputedColumnSql("GetUtcDate()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ESTADO");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("APLICACION");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFICADOR");

                    b.Property<Guid>("WorkerCode")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TRABAJADOR");

                    b.HasKey("Username", "Password");

                    b.HasIndex("WorkerCode");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("ApiAmaz.Model.Worker", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREADOR");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHACREACION");

                    b.Property<DateTime>("DateUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHAMODIFICACION")
                        .HasComputedColumnSql("GetUtcDate()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOMBRE");

                    b.Property<Guid>("RoleCode")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ROL");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFICADOR");

                    b.Property<bool>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ESTADO");

                    b.HasKey("Code");

                    b.HasIndex("RoleCode");

                    b.ToTable("TRABAJADOR", (string)null);

                    b.HasData(
                        new
                        {
                            Code = new Guid("dcecaf47-895a-4adb-92b5-0a62336619fc"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 3, 4, 719, DateTimeKind.Local).AddTicks(1168),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marcodlc10@gmail.com",
                            Name = "admin zeus",
                            RoleCode = new Guid("dcecaf47-895a-4adb-92b5-0a62336619eb"),
                            Updater = "admin",
                            isActive = false
                        });
                });

            modelBuilder.Entity("ApiAmaz.Model.User", b =>
                {
                    b.HasOne("ApiAmaz.Model.Worker", "Worker")
                        .WithMany("Users")
                        .HasForeignKey("WorkerCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ApiAmaz.Model.Worker", b =>
                {
                    b.HasOne("ApiAmaz.Model.Role", "Role")
                        .WithMany("Workers")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ApiAmaz.Model.Role", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("ApiAmaz.Model.Worker", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
