// <auto-generated />
using System;
using ApiAmaz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiAmaz.Migrations
{
    [DbContext(typeof(AmazDbContext))]
    partial class AmazDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiAmaz.Model.IdentityDocumentType", b =>
                {
                    b.Property<string>("DocumentType")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("TIPODOCUMENTO");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREADOR");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHACREACION");

                    b.Property<DateTime>("DateUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHAMODIFICACION")
                        .HasComputedColumnSql("GetUtcDate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("NameShort")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOMBRECORTO");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFICADOR");

                    b.Property<bool>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ESTADO");

                    b.HasKey("DocumentType");

                    b.ToTable("TIPODOCUMENTOIDENTIDAD", (string)null);

                    b.HasData(
                        new
                        {
                            DocumentType = "00",
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 647, DateTimeKind.Local).AddTicks(3644),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OTROS",
                            NameShort = "OTROS",
                            Updater = "admin",
                            isActive = false
                        },
                        new
                        {
                            DocumentType = "01",
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 647, DateTimeKind.Local).AddTicks(3653),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LIBRETA ELECTORAL O DNI",
                            NameShort = "L.E / DNI",
                            Updater = "admin",
                            isActive = false
                        },
                        new
                        {
                            DocumentType = "04",
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 647, DateTimeKind.Local).AddTicks(3656),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CARNET DE EXTRANJERIA",
                            NameShort = "CARNET EXT.",
                            Updater = "admin",
                            isActive = false
                        },
                        new
                        {
                            DocumentType = "06",
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 647, DateTimeKind.Local).AddTicks(3657),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "REG. UNICO DE CONTRIBUYENTES",
                            NameShort = "RUC",
                            Updater = "admin",
                            isActive = false
                        },
                        new
                        {
                            DocumentType = "07",
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 647, DateTimeKind.Local).AddTicks(3659),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PASAPORTE",
                            NameShort = "PASAPORTE",
                            Updater = "admin",
                            isActive = false
                        },
                        new
                        {
                            DocumentType = "11",
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 647, DateTimeKind.Local).AddTicks(3662),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PART. DE NACIMIENTO-IDENTIDAD",
                            NameShort = "P. NAC.",
                            Updater = "admin",
                            isActive = false
                        });
                });

            modelBuilder.Entity("ApiAmaz.Model.Role", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREADOR");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHACREACION");

                    b.Property<DateTime>("DateUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHAMODIFICACION")
                        .HasComputedColumnSql("GetUtcDate()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ESTADO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFICADOR");

                    b.HasKey("Code");

                    b.ToTable("ROL", (string)null);

                    b.HasData(
                        new
                        {
                            Code = new Guid("7bd887ab-bdff-4318-af2e-57cef3c703d1"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 646, DateTimeKind.Local).AddTicks(6954),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "VENDEDOR",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("9be1fa1b-a181-4e0b-a54b-0c02e8498a6f"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 646, DateTimeKind.Local).AddTicks(7070),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "ESTILISTA",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("6e96f41d-ae75-471f-9151-1099ecee7bd3"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 646, DateTimeKind.Local).AddTicks(7073),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "MARKETING",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("95ee6172-14ed-480a-b3d3-c2a72d5001cd"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 646, DateTimeKind.Local).AddTicks(7075),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "DESPACHADOR",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("a4cd43c8-1c56-4710-868c-41c7b9b43329"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 646, DateTimeKind.Local).AddTicks(7078),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "COBRANZA",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("ee737f28-102c-4113-b72f-5f871fb20df5"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 646, DateTimeKind.Local).AddTicks(7085),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "ADMINISTRATIVO",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("a66ae1ba-7121-481a-a171-ae8fc9570078"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 646, DateTimeKind.Local).AddTicks(7087),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "GERENTE COMERCIAL",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("7b092baa-acdc-47dd-ab74-69a9dc84b2cc"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 646, DateTimeKind.Local).AddTicks(7107),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "GERENTE GENERAL",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("ef37dca1-358b-44cb-934e-cdf34a3988a7"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 646, DateTimeKind.Local).AddTicks(7109),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "VENDEDOR FREE",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("4dd3a199-3f3f-4515-9758-d691644012c5"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 646, DateTimeKind.Local).AddTicks(7113),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "COORDINADOR",
                            Updater = "admin"
                        },
                        new
                        {
                            Code = new Guid("dcecaf47-895a-4adb-92b5-0a62336619eb"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 646, DateTimeKind.Local).AddTicks(7130),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "SUPERADMIN",
                            Updater = "admin"
                        });
                });

            modelBuilder.Entity("ApiAmaz.Model.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USUARIO");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CLAVE");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREADOR");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHACREACION");

                    b.Property<DateTime>("DateUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHAMODIFICACION")
                        .HasComputedColumnSql("GetUtcDate()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ESTADO");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("APLICACION");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFICADOR");

                    b.Property<Guid>("WorkerCode")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TRABAJADOR");

                    b.HasKey("Username", "Password");

                    b.HasIndex("WorkerCode");

                    b.ToTable("USUARIO", (string)null);

                    b.HasData(
                        new
                        {
                            Username = "admin",
                            Password = "default",
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 648, DateTimeKind.Local).AddTicks(3469),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SoftwareName = "WebAmaz",
                            Updater = "admin",
                            WorkerCode = new Guid("dcecaf47-895a-4adb-92b5-0a62336619fc")
                        });
                });

            modelBuilder.Entity("ApiAmaz.Model.Worker", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREADOR");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHACREACION");

                    b.Property<DateTime>("DateUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHAMODIFICACION")
                        .HasComputedColumnSql("GetUtcDate()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOMBRE");

                    b.Property<Guid>("RoleCode")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ROL");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFICADOR");

                    b.Property<bool>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ESTADO");

                    b.HasKey("Code");

                    b.HasIndex("RoleCode");

                    b.ToTable("TRABAJADOR", (string)null);

                    b.HasData(
                        new
                        {
                            Code = new Guid("dcecaf47-895a-4adb-92b5-0a62336619fc"),
                            Creator = "admin",
                            DateCreated = new DateTime(2022, 7, 27, 2, 4, 56, 647, DateTimeKind.Local).AddTicks(6030),
                            DateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marcodlc10@gmail.com",
                            Name = "admin zeus",
                            RoleCode = new Guid("dcecaf47-895a-4adb-92b5-0a62336619eb"),
                            Updater = "admin",
                            isActive = false
                        });
                });

            modelBuilder.Entity("ApiAmaz.Model.User", b =>
                {
                    b.HasOne("ApiAmaz.Model.Worker", "Worker")
                        .WithMany("Users")
                        .HasForeignKey("WorkerCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ApiAmaz.Model.Worker", b =>
                {
                    b.HasOne("ApiAmaz.Model.Role", "Role")
                        .WithMany("Workers")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ApiAmaz.Model.Role", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("ApiAmaz.Model.Worker", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
